apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: racheeka/auth
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: racheeka/client
      context: client
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/auth-depl.yaml
    - infra/ingress-srv.yaml
    - infra/auth-mongo-depl.yaml
    - infra/client-depl.yaml
