apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: racheeka/orders
        imagePullPolicy: Never
        env:
          - name: NATS_URL
            value: http://nats-srv:4222
          - name: NATS_CLUSTERID
            value: ticketing
          - name: NATS_CLIENTID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: JWT_KEY
            valueFrom: 
              secretKeyRef:
                name: jwt-secret
                key: jwt
          - name: MONGO_URI
            value: mongodb://orders-mongo-srv:27017/orders
---

apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
  - port: 3000
    targetPort: 3000