apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: racheeka/payments
        imagePullPolicy: Never
        env:
          - name: NATS_URL
            value: http://nats-srv:4222
          - name: NATS_CLUSTERID
            value: ticketing
          - name: NATS_CLIENTID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: JWT_KEY
            valueFrom: 
              secretKeyRef:
                name: jwt-secret
                key: jwt
          - name: MONGO_URI
            value: mongodb://payments-mongo-srv:27017/payments
---

apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
  - port: 3000
    targetPort: 3000

