import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getCurrentUser } from "./lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const result = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col h-screen">
          <div className="h-14 flex justify-between pt-2">
            <h2 id="logo" className="px-5 text-3xl font-bold text-white">
              Ticketing
            </h2>
            <nav className="px-4">
              {result.currentUser ? (
                <div className="flex justify-between">
                  <a className="m-2 cursor-pointer" href="/auth/signout">
                    Sign Out
                  </a>
                </div>
              ) : (
                <div className="flex justify-between">
                  <a className="m-2 cursor-pointer" href="/auth/signup">
                    Signup
                  </a>
                  <a className="m-2 cursor-pointer" href="/auth/signin">
                    Signin
                  </a>
                </div>
              )}
            </nav>
          </div>
          <hr />
          {children}
        </main>
      </body>
    </html>
  );
}
